# config/database.yml
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: mysqlpass
  socket: /var/run/mysqld/mysqld.sock
  ssl_mode: :disabled
  sslverify: false

development:
  <<: *default
  database: classcontrol_development

test:
  <<: *default
  database: classcontrol_test

# PRODUCCIÃ“N CON TODAS LAS CONEXIONES
production:
  primary:
    adapter: mysql2
    encoding: utf8mb4
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: avnadmin
    password: <%= ENV["MYSQL_PASSWORD"] %>
    host: <%= ENV["MYSQL_HOST"] %>
    port: 3306
    database: defaultdb
    ssl_mode: :verify_identity
    sslca: /etc/ssl/certs/ca-certificates.crt

  cable:
    adapter: mysql2
    encoding: utf8mb4
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: avnadmin
    password: <%= ENV["MYSQL_PASSWORD"] %>
    host: <%= ENV["MYSQL_HOST"] %>
    port: 3306
    database: defaultdb
    ssl_mode: :verify_identity
    sslca: /etc/ssl/certs/ca-certificates.crt

  queue:
    adapter: mysql2
    encoding: utf8mb4
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: avnadmin
    password: <%= ENV["MYSQL_PASSWORD"] %>
    host: <%= ENV["MYSQL_HOST"] %>
    port: 3306
    database: defaultdb
    ssl_mode: :verify_identity
    sslca: /etc/ssl/certs/ca-certificates.crt

  cache:
    adapter: mysql2
    encoding: utf8mb4
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: avnadmin
    password: <%= ENV["MYSQL_PASSWORD"] %>
    host: <%= ENV["MYSQL_HOST"] %>
    port: 3306
    database: defaultdb
    ssl_mode: :verify_identity
    sslca: /etc/ssl/certs/ca-certificates.crt
