# config/database.yml
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: classcontrol_development
  username: root
  password: mysqlpass
  socket: /var/run/mysqld/mysqld.sock

test:
  <<: *default
  database: classcontrol_test
  username: root
  password: mysqlpass
  socket: /var/run/mysqld/mysqld.sock

# PRODUCCIÃ“N SIMPLE - Usa variables de entorno
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  # O si prefieres variables separadas:
  # host: <%= ENV['MYSQL_HOST'] %>
  # port: <%= ENV['MYSQL_PORT'] || 3306 %>
  # username: <%= ENV['MYSQL_USER'] %>
  # password: <%= ENV['MYSQL_PASSWORD'] %>
  # database: <%= ENV['MYSQL_DATABASE'] %>
  # ssl_mode: :verify_identity
